trigger:
- main

variables:
  imageName: 'prmd77/frontend-app-templat'
  tag: '$(Build.BuildId)'

stages:
- template: templates/build.yml
  parameters:
    imageName: $(imageName)
    tag: $(tag)

- template: templates/push.yml
  parameters:
    imageName: $(imageName)
    tag: $(tag)
    dockerRegistryServiceConnection: 'docker-registry-service-connection'

# - template: templates/deploy.yml
#   parameters:
#     imageName: $(imageName)
#     tag: $(tag)
#     aksServiceConnection: 'aks-connection'