apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsurge-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudsurge
  template:
    metadata:
      labels: 
        app: cloudsurge
    spec:
      containers:
        - name: cloudsurge-container
          image: prmd77/cloudsurgeimag:306
          ports:
             - containerPort: 80
      imagePullSecrets:
        - name: dockerhub-secret
      
---
apiVersion: v1
kind: Service
metadata:
  name: cloudsurge-service
spec: 
  type: LoadBalancer
  selector: 
    app: cloudsurge 
  ports: 
    - port: 80
      targetPort: 80
